version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./dockerfile
      target: development
      args:
        app: gatway
    command: sleep 8000000 #npm run start:dev gatway
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - ../.env
    networks:
      - intelli-network
    # depends_on:
    #   - auth
    volumes:
      - .:/usr/src/app
    # command: npm run start:dev microservice-books-club # overrides CMD from dockerfile

  auth:
    build:
      context: .
      dockerfile: ./dockerfile
      target: development
      args:
        app: auth
    command: npm run start:dev auth
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - .:/usr/src/app

  user:
    build:
      context: .
      dockerfile: ./dockerfile
      target: development
      args:
        app: user
    command: npm run start:dev user
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - .:/usr/src/app

networks:
  intelli-network:
    driver: bridge
    # external: true
