version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/intelli-talent-nestjs-backend/dockerfile.dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - ../.env
    networks:
      - intelli-network

    depends_on:
      # - rabbitmq
      # - postgres
      - auth
      # - books
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev microservice-books-club # overrides CMD from dockerfile

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/dockerfile.dev
    restart: unless-stopped
    env_file:
      - ../.env
    # depends_on:
    # - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev auth # overrides CMD from dockerfile
    networks:
      - intelli-network

  user:
    build:
      context: .
      dockerfile: ./apps/user/dockerfile.dev
    restart: unless-stopped
    env_file:
      - ../.env
    # depends_on:
    #   - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev user # overrides CMD from dockerfile
    networks:
      - intelli-network

networks:
  intelli-network:
    external: true
