export const skills = [
  "Python",
  "Java",
  "C",
  "C++",
  "R",
  "MATLAB",
  "AI",
  "ML",
  "Front-end",
  "Back-end",
  "Generative AI",
  "Supervised Learning",
  "Reinforcement Learning",
  "Deep Learning",
  "Neural Networks",
  "Support Vector Machines",
  "Decision Trees",
  "Ensemble Learning",
  "Feature Engineering",
  "Hyperparameter Tuning",
  "Model Evaluation",
  "Data Cleaning",
  "Data Analysis",
  "Data Visualization",
  "Statistical Analysis",
  "Predictive Modeling",
  "Data Mining",
  "Big Data Technologies",
  "Hadoop",
  "Spark",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "Scikit-learn",
  "Theano",
  "Caffe",
  "NLP",
  "Natural Language Processing",
  "Text Processing",
  "Named Entity Recognition",
  "NER",
  "Sentiment Analysis",
  "Topic Modeling",
  "Language Translation",
  "Speech Recognition",
  "Computer Vision",
  "Image Processing",
  "Object Detection",
  "Image Classification",
  "Image Segmentation",
  "Facial Recognition",
  "Feature Extraction",
  "Deep Learning Architectures",
  "Convolutional Neural Networks",
  "CNN",
  "Recurrent Neural Networks",
  "RNN",
  "Generative Adversarial Networks",
  "GAN",
  "Transformer Models",
  "Autoencoders",
  "Markov Decision Processes",
  "MDP",
  "Q-Learning",
  "Policy Gradient Methods",
  "Deep Q-Networks",
  "DQN",
  "Algorithmic Complexity",
  "Optimization Techniques",
  "Parallel Computing",
  "Distributed Computing",
  "Version Control",
  "Git",
  "Subversion",
  "SVN",
  "Mercurial",
  "Hg",
  "Perforce",
  "Helix Core",
  "Team Foundation Version Control",
  "TFVC",
  "Bitbucket",
  "Apache Subversion",
  "Concurrent Versions System",
  "CVS",
  "SourceGear Vault",
  "Bazaar",
  "GitHub",
  "GitLab",
  "Azure DevOps",
  "AWS CodeCommit",
  "Google Cloud Source Repositories",
  "Perforce Helix TeamHub",
  "Beanstalk",
  "GitKraken",
  "RhodeCode",
  "Software Development Life Cycle",
  "Agile Methodologies",
  "DevOps Practices",
  "Linear Algebra",
  "Calculus",
  "Probability Theory",
  "Statistics",
  "Optimization",
  "Problem-Solving",
  "Critical Thinking",
  "C#",
  "Ruby",
  "JavaScript",
  "Node.js",
  "Go",
  "PHP",
  "Kotlin",
  "Scala",
  "Spring",
  "Django",
  "Flask",
  "ASP.NET",
  "Ruby on Rails",
  "Express.js",
  "Laravel",
  "Play Framework",
  "Gin",
  "SQL",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Microsoft SQL Server",
  "MSSQL",
  "NoSQL",
  "MongoDB",
  "Cassandra",
  "Redis",
  "Couchbase",
  "RESTful APIs",
  "GraphQL",
  "API design",
  "API documentation",
  "OpenAPI",
  "Swagger",
  "Linux system administration",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud Platform (GCP)",
  "Apache",
  "Nginx",
  "RabbitMQ",
  "Apache Kafka",
  "ZeroMQ",
  "Unit Testing",
  "Integration Testing",
  "Test Automation",
  "Performance Testing",
  "Secure coding practices",
  "Authentication and authorization",
  "OAuth",
  "JWT",
  "Encryption",
  "TLS",
  "SSL",
  "HTML",
  "CSS",
  "React.js",
  "Angular",
  "Vue.js",
  "Design patterns",
  "MVC",
  "Microservices",
  "RESTful architecture",
  "Scalability",
  "Performance optimization",
  "Continuous Integration and Deployment",
  "CI/CD",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "GitLab CI/CD",
  "Log management",
  "ELK stack",
  "Splunk",
  "Monitoring tools",
  "Prometheus",
  "Grafana",
  "Nagios",
  "Jira",
  "Trello",
  "Slack",
  "Microsoft Teams",
  "Debugging",
  "HTTP",
  "TCP/IP",
  "ASP.NET MVC",
  "ASP.NET Core",
  "Spring Boot",
  "Symfony",
  "Ember.js",
  "ASP.NET Web API",
  "FastAPI",
  "Hapi.js",
  "NestJS",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "SciPy",
  "React Native",
  "Flutter",
  "Xamarin",
  "Ionic",
  "NativeScript",
  "Unity",
  "Unreal Engine",
  "Godot Engine",
  "Phaser",
  "Cocos2d-x",
  "Bootstrap",
  "Material-UI",
  "MUI",
  "Semantic UI",
  "Foundation",
  "Tailwind CSS",
  "Jest",
  "Pytest",
  "JUnit",
  "NUnit",
  "Selenium",
  "Cypress",
  ".NET Core",
  "RubyMotion",
  "Serverless Framework",
  "Server-side Swift",
  "Vapor",
  "Microservices Framework",
  "Seneca",
  "Moleculer",
  "Amazon Web Services",
  "Microsoft Azure",
  "Google Cloud Platform",
  "GCP",
  "IBM Cloud",
  "Oracle Cloud Infrastructure",
  "OCI",
  "Terraform",
  "AWS CloudFormation",
  "Azure Resource Manager",
  "ARM",
  "Google Cloud Deployment Manager",
  "Ansible",
  "Amazon ECS/EKS",
  "Azure Kubernetes Service",
  "AKS",
  "Google Kubernetes Engine",
  "GKE",
  "Virtual Private Cloud",
  "VPC",
  "Subnets",
  "CIDR blocks",
  "VPN",
  "Load Balancers",
  "ELB",
  "ALB",
  "NLB",
  "DNS Management",
  "CloudWatch",
  "Azure Monitor",
  "Stackdriver",
  "Elasticsearch",
  "Logstash",
  "Kibana",
  "Amazon S3",
  "Azure Blob Storage",
  "Google Cloud Storage",
  "Amazon RDS",
  "Azure SQL Database",
  "Google Cloud SQL",
  "NoSQL Databases",
  "DynamoDB",
  "Cosmos DB",
  "Bigtable",
  "Managed Database Services",
  "AWS Lambda",
  "Azure Functions",
  "Google Cloud Functions",
  "Bash Scripting",
  "PowerShell",
  "Cloud SDKs and CLIs",
  "Firewall configuration",
  "Firewall management",
  "Intrusion Detection",
  "Prevention Systems",
  "Network Segmentation",
  "VPN configuration",
  "VPN management",
  "Anti-virus",
  "Anti-malware",
  "Endpoint Detection and Response (EDR)",
  "Patch Management",
  "Device Encryption",
  "Role-based access control",
  "Multi-factor authentication",
  "Privileged Access Management",
  "Nessus",
  "Qualys",
  "Penetration testing",
  "Tableau",
  "Power BI",
  "Data Cleaning and Preparation",
  "Excel",
  "Business Intelligence Tools",
  "Responsive Web Design",
  "CSS Preprocessing",
  "Sass",
  "Less",
  "Browser Developer Tools",
  "Webpack",
  "Gulp",
  "Grunt",
  "AJAX",
  "Progressive Web Apps",
  "PWAs",
  "Web Accessibility",
  "SEO Basics",
  "UI/UX Principles",
  "Graphic Design Skills",
  "Mocha",
  "Materialize CSS",
  "jQuery",
  "Next.js",
  "Prisma",
  "Gatsby",
  "Svelte",
  "Sinatra",
  "Network Administration",
  "System Administration",
  "Troubleshooting",
  "Hardware Maintenance",
  "Software Installation and Configuration",
  "Cybersecurity Knowledge",
  "Database Management",
  "Cloud Computing Knowledge",
  "IT Infrastructure Management",
  "IT Security Management",
  "Backup and Recovery",
  "Virtualization",
  "Monitoring and Maintenance",
  "Scripting and Automation",
  "Documentation and Reporting",
  "Project Management",
  "Time Management",
  "Active Directory",
  "Cisco Networking Equipment",
  "Windows Server",
  "Linux Operating Systems",
  "VMware",
  "Hyper-V",
  "G Suite",
  "Microsoft Office 365",
  "Wireshark",
  "Puppet",
  "Chef",
  "JIRA",
  "Object-Oriented Programming",
  "OOP",
  "Data Structures and Algorithms",
  "Java Standard Edition",
  "Java SE",
  "Java Enterprise Edition",
  "Jakarta EE",
  "Spring Framework",
  "Hibernate Framework",
  "RESTful Web Services",
  "SOAP Web Services",
  "JavaServer Pages",
  "JSP",
  "Servlets",
  "Java Database Connectivity",
  "JDBC",
  "Maven",
  "Gradle",
  "Test-Driven Development",
  "TDD",
  "Scrum",
  "Kanban",
  "IntelliJ IDEA",
  "Eclipse",
  "NetBeans",
  "Apache Tomcat",
  "Jetty",
  "JBoss Application Server",
  "WildFly",
  "Apache Maven",
  "Apache Struts",
  "Apache Camel",
  "Mockito",
  "PowerMock",
  "SonarQube",
  "Seaborn",
  "Jupyter Notebook",
  "Apache Spark",
  "AWS SageMaker",
  "XGBoost",
  "LightGBM",
  "CatBoost",
  "OpenCV",
  "NLTK",
  "Swift",
  "Objective-C",
  "Dart",
  "User Interface Design",
  "UI Design",
  "User Experience Design",
  "Wireframing and Prototyping",
  "Material Design",
  "Human Interface Guidelines",
  "Model-View-Controller",
  "MVVM",
  "Model-View-ViewModel",
  "MVP",
  "Model-View-Presenter",
  "Clean Architecture",
  "Realm",
  "Firebase Realtime Database",
  "Firebase Firestore",
  "Bitrise",
  "Fastlane",
  "Android Studio",
  "Xcode",
  "Flutter SDK",
  "React Native CLI",
  "Ionic CLI",
  "Firebase",
  "Realm Database",
  "CocoaPods",
  "Android SDK",
  "iOS SDK",
  "Appium",
  "UDP",
  "DNS",
  "DHCP",
  "SNMP",
  "Firewalls",
  "VPNs",
  "IDS/IPS",
  "ACLs",
  "Routing and Switching",
  "LAN/WAN Management",
  "VLANs and Subnetting",
  "Wireless Networking",
  "Network Monitoring and Troubleshooting",
  "Network Performance Optimization",
  "Network Configuration and Management",
  "Network Virtualization",
  "Load Balancing",
  "Cloud Networking",
  "Voice over Internet Protocol",
  "VoIP",
  "Cisco Packet Tracer",
  "Cisco CLI",
  "SolarWinds Network Performance Monitor",
  "Zabbix",
  "PRTG Network Monitor",
  "NetFlow Analyzer",
  "Nmap",
  "GNS3",
  "Cisco IOS",
  "Juniper JunOS",
  "OpenVPN",
  "IPsec",
  "OpenNMS",
  "Microsoft Visio",
  "VMware NSX",
  "PyCharm",
  "SQLAlchemy",
  "Jasmine",
  "Sphinx",
  "Doxygen",
  "MkDocs",
  "ESLint",
  "Pylint",
  "Checkstyle",
  "npm",
  "pip",
  "NuGet",
  "Windows",
  "macOS",
  "Linux",
  "Zendesk",
  "Jira Service Desk",
  "Freshdesk",
  "ServiceNow",
  "TeamViewer",
  "AnyDesk",
  "Zoom",
  "Skype",
  "Confluence",
  "SharePoint",
  "Wiki Systems",
  "SolarWinds",
  "PuTTY",
  "SSH",
  "VNC",
  "Ping",
  "Traceroute",
  "WiresharkSalesforce",
  "HubSpot",
  "Zoho CRM",
  "Camtasia",
  "Snagit",
  "Loom",
  "Word",
  "PowerPoint",
  "Adobe Acrobat",
  "Ubuntu",
  "CentOS",
  "Red Hat",
  "Unix",
  "VMware vSphere",
  "KVM",
  "Bash",
  "Microsoft Project",
  "Asana",
];
