export const FilterationServicePattern = {
    filterJob: 'filterJob',
    beginCurrentStage: 'beginCurrentStage',
    getUserStage: 'getUserStage',
    getAppliedUsers: 'getAppliedUsers',
    submitInterview: 'submitInterview',
    reviewInterview: 'reviewInterview',
    selectProfile: 'selectProfile',
    getMatchedJobs: 'getMatchedJobs',
    getAppliedJobs: 'getAppliedJobs',
    getInterviewQuestions: 'getInterviewQuestions',
    getJobApplicants: 'getJobApplicants',
    getInterviewAnswers: 'getInterviewAnswers',
    getInterviewedApplicants: 'getInterviewedApplicants',
    getUserInterviews: 'getUserInterviews',
    getUserInterviewStats: 'getUserInterviewStats',
    deleteProfile: 'deleteProfile',
};
