export const FilterationServicePattern = {
    filterJob: 'filterJob',
    beginCurrentStage: 'beginCurrentStage',
    getUserStage: 'getUserStage',
    getAppliedUsers: 'getAppliedUsers',
    passQuiz: 'passQuiz',
    failQuiz: 'failQuiz',
    submitInterview: 'submitInterview',
    reviewInterview: 'reviewInterview',
    selectProfile: 'selectProfile',
    getMatchedJobs: 'getMatchedJobs',
    getAppliedJobs: 'getAppliedJobs',
    getInterviewQuestions: 'getInterviewQuestions',
    getJobApplicants: 'getJobApplicants',
    getInterviewAnswers: 'getInterviewAnswers',
};
